name: coverage markdown

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-coverage:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node:
          - 18.14.2
        pnpm:
          - 7
    runs-on: ${{ matrix.os }}

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: 'Run test coverage'
        run: yarn test:coverage

      - name: Hyperse Vitest Coverage Reporter
        uses: hyperse-io/vitest-coverage-reporter@v1.0.5

