name: github pages

on:
  push:
    branches: 
      - main  # Set a branch name to trigger deployment
      


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [20.x]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        working-directory: website
        run: |
          yarn build

      - name: Unit tests
        working-directory: website
        run: |
          yarn test

      - name: Deploy
        working-directory: website
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build